### PR TITLE
Added %folder% param to custom option

### PR DESCRIPTION
**Pull request by marska**
- Added option {folder} to custom command argument. Some applications don't get path from process working directory. For example cmder.
After that change I can use custom comand: cmder.exe with argument: /START {folder}

### CODE REVIEW

**Comment by marska** [comment]
I changed folder param to %folder%. Added description. Added configuration for cmdr.

**Comment by madskristensen** [comment]
I like the PR for the %folder% features, but can you separate the NuGet packages out. I'm not sure I like the use of those

**Comment by marska** [comment]
OK, I reverted that.

**Comment by madskristensen** [comment]
Thanks. This is great!

**Comment by madskristensen** [comment]
Should we add this support in the Presets dropdown to make it easy for people to use `cmder`?

**Comment by marska** [comment]
:+1: Thanks!

**Pull request merged**
