### PR TITLE
Expand environment variables and allow passing of "folderpath" to command line.

### PR DESCRIPTION
**Pull request by cklutz**
Added options:
- Replace environment variables (%VAR%) in "command" and "arguments".
- Allow a special token-string in the arguments, that will be replaced with the target folder path (i.e. allow to pass the target folder other than by "Process.WorkingDirectory" only)

### CODE REVIEW

**Comment by madskristensen** [comment]
That's a great idea!! I can't auto-merge this. Can you please do a rebase and submit it again?

**Comment by cklutz** [comment]
Hi, will do as soon as possible. I'm currently at work with limited
internet access :-(

On Thu, Jan 22, 2015 at 7:37 AM, Mads Kristensen <notifications@github.com>
wrote:

> That's a great idea!! I can't auto-merge this. Can you please do a rebase
> and submit it again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madskristensen/OpenCommandLine/pull/5#issuecomment-70977899>
> .
>



-- 
Christian

**Comment by cklutz** [comment]
OK, I "attempted" to rebase my changes (I'm rather new to Git so things might not be quite right ;-)
BTW, I just saw that my pull request also contains a change to the .csproj file. Although it "works for me" I'm not sure if you want to have that.

**Comment by madskristensen** [comment]
Why have a setting for replacing env variables instead of always doing it. When don't you want %system% to be resolved?

**Comment by cklutz** [comment]
Why, I don't know. It is no use case for my, but I thought it would be good to be conservative. The default could certainly be to always replace them, unless otherwise configured.

**Comment by madskristensen** [comment]
Good point. Thanks for the PR

**Pull request merged**
